# Generated by Django 3.1.1 on 2020-09-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20200917_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='card_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='meal',
            name='code',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='meal',
            name='fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='proteins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='bruto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='neto',
            field=models.IntegerField(default=0),
        ),
    ]
