# Generated by Django 3.1.1 on 2020-09-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20200917_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='bruto',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='neto',
            field=models.IntegerField(default=0),
        ),
    ]
