# Generated by Django 3.1.1 on 2020-09-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_auto_20200919_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cook',
        ),
    ]
