# Generated by Django 3.1.1 on 2020-09-21 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_cook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('MEAL', 'meal'), ('PRODUCT', 'product'), ('UNDEFINED', 'undefined')], default='UNDEFINED', max_length=30),
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.category'),
        ),
    ]
